config/routes.rb
Rails.application.routes.draw do

	resources :subtasks

  resources :tasks do
  	member do
  		get :mark_complete
  	end
  end

  devise_for :users
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  VALID_NAME_REGEX = /\A([a-z]|[A-Z]|[0-9]|[!*&@!#%$^+-.,\'\" ])+\z/

  validates :body, presence: true,
            length: { maximum: 128 },
            format: { with: VALID_NAME_REGEX }

  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord 
  VALID_NAME_REGEX = /\A([a-z]|[A-Z]|[0-9]|[!*&@!#%$^+-.,\'\" ])+\z/

  validates :body, presence: true,
            length: { maximum: 128 },
            format: { with: VALID_NAME_REGEX }

  belongs_to :user
  has_many   :subtasks, dependent: :destroy

  scope :public_tasks,  -> { includes(:subtasks).where(is_private: false) }
  scope :private_tasks, -> { includes(:subtasks).where(is_private: true) }

  def private
  	self.is_private ? "Private" : "Public"
  end

  def user_name
  	self.is_private ? "" : self.user.first_name + " " + self.user.last_name
  end

  def status
    self.completed ? "Completed: Yes" : "Completed: No"
  end

  def display_completed
    "(Completed)"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_NAME_REGEX = /\A([a-z]|[A-Z]|[0-9]|[-._])+\z/

  validates :first_name, presence: true,
            length: { maximum: 64 },
            format: { with: VALID_NAME_REGEX }

  validates :last_name, presence: true,
            length: { maximum: 64 },
            format: { with: VALID_NAME_REGEX }

  has_many :tasks, dependent: :destroy

  def full_name
    self.first_name + " " + self.last_name
  end

  def greeting
    "Hello " + self.full_name + ", " + self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  include TasksHelper

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :current_password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :current_password])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
  	if user_signed_in?
  		@public_tasks = Task.public_tasks.order(created_at: :desc)
  		@private_tasks = Task.private_tasks.where(user_id: current_user.id).order(created_at: :desc)
    end
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
	before_action :authenticate_user!
	before_action :set_subtask, only: [:edit, :update, :destroy]

	respond_to :html
	respond_to :js

	def new
		@task = Task.find(params[:task_id])
		@subtask = @task.subtasks.build
		respond_with(@subtasks)
	end

	def create
		task = Task.find(params[:task_id])
		@subtask = task.subtasks.build(subtask_params)

		@subtask.save
		respond_with(@subtask)
	end

	def edit

	end

	def update
		@subtask.update(subtask_params)
		respond_with(@subtask)
	end

  def destroy
    @subtask.destroy
    respond_with(@subtask)
  end

	private
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    def subtask_params
      params.require(:subtask).permit(:body, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:edit, :update, :destroy, :mark_complete]

  def index
    @my_public_tasks = Task.public_tasks.where(user_id: current_user.id).order(created_at: :desc)
    @my_private_tasks = Task.private_tasks.where(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @task = Task.includes(:subtasks).find(params[:id])
    @is_private = @task.is_private ? "Private" : "Public"
    @subtasks = @task.subtasks
  end

  def new
    @task = current_user.tasks.build
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash.now[:success] = "task was successfully created."
      redirect_to tasks_url
    else
      render :new
    end
  end

  def update
    if item_owner?(current_user, @task)
      if @task.update(task_params)
        flash[:success] = "task was successfully updated."
        redirect_to @task
      else
        render :edit
      end
    else
      flash[:warning] = "You can only edit your own tasks."
      redirect_to @task
    end
  end

  def destroy
    if item_owner?(current_user, @task)
      @task.destroy
      flash.now[:success] = "task was successfully deleted."
      redirect_to tasks_url
    else
      flash[:warning] = "You can only delete your own tasks."
      redirect_to @task
    end
  end

  def mark_complete
    @task.update_attributes(completed: true)
    redirect_to @task
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:body, :is_private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/tasks_helper.rb
module TasksHelper
	def item_owner?(user, item)
		user == item.user
	end
end

app/views/home/index.html.erb
  <% if user_signed_in? %>
    <h1>All Tasks</h1> 
    <%= render 'layouts/shared_links' %>
  <% else %>
    <h1>Welcome to Personal Organizer</h1> 
  <% end %>  

  <% if user_signed_in? %>
    <% if @public_tasks.count < 1 && @private_tasks.count < 1 %>
      <p class="center">
        No tasks yet. Click <%= link_to "here", new_task_path %> to create one
      </p>
    <% end %>

    <% if @public_tasks.count > 0 %>
      <p><strong>Public Tasks</strong></p>
      <ul>
        <% @public_tasks.each do |task| %>
          <li>
            <%= task.created_at.strftime('%F') %>
            <%= task.created_at.strftime('%H:%M %p') %>,
            <%= link_to task.body, task %>
            <%= "(by #{task.user_name})" unless current_user.id == task.user_id %> 
            <%= task.display_completed if task.completed %>
          </li>

          <div class="my_subtasks">
            <% task.subtasks.each do |subtask| %>
              <%= render  partial: "subtasks/subtask", locals: {subtask: subtask} %>
            <% end %>
          </div>
        <% end %>
      </ul>
    <% end %><br><br>

    <% if @private_tasks.count > 0 %>
      <p><strong>Private Tasks</strong></p>
      <ul>
        <% @private_tasks.each do |task| %>
          <li>
            <%= task.created_at.strftime('%F') %>
            <%= task.created_at.strftime('%H:%M %p') %>,
            <%= link_to task.body, task %>
            <%= task.display_completed if task.completed %>
          </li>

          <div class="my_subtasks">
            <% task.subtasks.each do |subtask| %>
              <%= render  partial: "subtasks/subtask", locals: {subtask: subtask} %>
            <% end %>
          </div>
        <% end %>
      </ul>
    <% end %><br><br>

  <% else %>
    <p class="center">
      Please sign in or sign up to get started
    </p>
<!--     <p class="center">
      Please 
      <%= link_to "Sign Me In", new_user_session_path %> or 
      <%= link_to "Sign Me Up", new_user_registration_path %> to get started
    </p> -->
  <% end %>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="greeting"><%= link_to current_user.greeting, tasks_url %></li>
              <li class="profile"><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li class="signout"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="signin"><%= link_to "Sign In", new_user_session_path %></li>
              <li class="signup"><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shared_links.html.erb
<p class="center">
  <%= link_to 'My Tasks', tasks_path %> |
  <%= link_to 'All Tasks', root_path %> |
  <%= link_to "Create New Task", new_task_path %>
</p><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalOrganizer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container" ><br><br>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/subtasks/_edit_form.html.erb
<%= form_with(model: @subtask) do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
        <% @subtask.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :body, label: false, autofocus: true, placeholder: "Subtask" %>
  </div>

  <div class="actions">
    <%= f.submit "Save Change", class: "btn btn-primary" %>
  </div>

  <div class="center">
    <%= link_to 'Cancel', '#', class: 'cancel-link' %>
  </div>
<% end %>

app/views/subtasks/_form.html.erb
<%= form_with(model: @subtask) do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
        <% @subtask.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= f.label :body %> (Valid characters includes: numbers, letters, spaces, !@#$%^&*_+,.'")</p>
    <%= f.text_field :body, label: false, autofocus: true, placeholder: "Subtask" %>
  </div>

  <%= hidden_field_tag 'task_id', @task.id %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

  <div class="center">
    <%= link_to 'Cancel', '#', class: 'cancel-link' %>
  </div>
<% end %>

app/views/subtasks/_subtask.html.erb
<%= div_for subtask do %>
  <p>
  	<%= subtask.created_at.localtime.strftime('%F') %> 
    <%= subtask.created_at.localtime.strftime('%H:%M %p') %>,
  	<%= subtask.body %>
	<% if item_owner?(current_user, subtask.task) %>
      <%= link_to "Edit", edit_subtask_path(subtask), remote: true %> |
      <%= link_to "Delete", subtask, remote: true, method: :delete, data: { confirm: "Click Ok to confirm" } %>
    <% end %>
  </p>
<% end %>

app/views/subtasks/_subtask_show.html.erb
<%= div_for subtask do %>
  <p>
  	<%= subtask.created_at.localtime.strftime('%F') %> 
    <%= subtask.created_at.localtime.strftime('%H:%M %p') %>,
  	<%= subtask.body %>
  	<% if item_owner?(current_user, subtask.task) %>
      <%= link_to "Edit", edit_subtask_path(subtask), remote: true %> |
      <%= link_to "Delete", subtask, remote: true, method: :delete, data: { confirm: "Click Ok to confirm" } %>
    <% end %>
  </p>
<% end %>

app/views/subtasks/complete.js.erb
$('div#<%= dom_id(@subtask) %>').fadeOut();
$('.complete_task').append('<%= j render partial: “subtask”, locals: {subtask: @subtask} %>');
$('div#<%= dom_id(@subtask) %>').find('h3').css('text-decoration', 'line-through');

app/views/subtasks/create.js.erb
$('form').hide();
$('.my_subtasks').append('<%= j render partial: "subtask", locals: {subtask: @subtask} %>');
$('.new_subtask_button').show();

app/views/subtasks/destroy.js.erb
$('div#<%= dom_id(@subtask) %>').remove();

app/views/subtasks/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@subtask) %>').append('<%= j render("edit_form") %>');

app/views/subtasks/new.js.erb
$('.new_subtask_button').after('<%= j render('form') %>');
$('.new_subtask_button').hide();

app/views/subtasks/update.js.erb
$('form').hide();
$('div#<%= dom_id(@subtask) %>').replaceWith('<%= j render partial: "subtask", locals: {subtask: @subtask} %>').reload();

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :body %> (required)
  <%= form.text_field :body, id: :task_body, autofocus: true %>

  <p><strong>Private</strong><%= form.check_box :is_private %></p>

  <p><%= form.submit class: "btn btn-primary" %></p>
  <p class="center"><%= link_to 'Cancel', root_url %></p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'layouts/shared_links' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_with(model: @task, local: true) do |form| %>
	  <% if @task.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

	      <ul>
	        <% @task.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <%= form.label :body, "Name" %> (required)
	  <%= form.text_field :body, id: :task_body, autofocus: true %>

	  <p><strong>Private</strong><%= form.check_box :is_private %></p>

	  <p><%= form.submit "Save Changes", class: "btn btn-primary" %></p>
	  <p class="center"><%= link_to 'Cancel', @task %></p>
	<% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<%= render 'layouts/shared_links' %>

<% if @my_public_tasks.count > 0 %>
  <p><strong>Public Tasks</strong></p>
  <ul>
    <% @my_public_tasks.each do |task| %>
      <li>
        <%= task.created_at.localtime.strftime('%F') %>
        <%= task.created_at.localtime.strftime('%H:%M %p') %>,
        <%= link_to task.body, task %>
        <%= "(by #{task.user_name})" unless current_user.id == task.user_id %> 
        <%= task.display_completed if task.completed %>
      </li>
      <div class="my_subtasks">
        <% task.subtasks.each do |subtask| %>
          <%= render  partial: "subtasks/subtask", locals: {subtask: subtask} %>
        <% end %>
      </div>
    <% end %>
  </ul>
<% end %><br><br>

<% if @my_private_tasks.count > 0 %>
  <p><strong>Private Tasks</strong></p>
  <ul>
    <% @my_private_tasks.each do |task| %>
      <li>
        <%= task.created_at.localtime.strftime('%F') %>
        <%= task.created_at.localtime.strftime('%H:%M %p') %>,
        <%= link_to task.body, task %>
        <%= task.display_completed if task.completed %>
      </li>

      <div class="my_subtasks">
        <% task.subtasks.each do |subtask| %>
          <%= render  partial: "subtasks/subtask", locals: {subtask: subtask} %>
        <% end %>
      </div>
    <% end %>
  </ul>
<% else %>
  <p class="center">Please <%= link_to "create a task", new_task_path %> first</p>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'layouts/shared_links' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= render 'form', task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<h1>View Task Details</h1>
<%= render 'layouts/shared_links' %>

  <p><strong><%= @task.status %></strong></p>
  <%= @task.created_at.localtime.strftime('%F') %>
  <%= @task.created_at.localtime.strftime('%H:%M %p') %>,
  <%= @is_private %> Task,
  <%= @task.body %>

  <% if item_owner?(current_user, @task) %>
    <% unless @task.completed %>
      <%= link_to 'Mark Complete', mark_complete_task_path(@task), data: { confirm: 'Click ok to comfirm' } %> |
    <% end %>
    <%= link_to 'Edit', edit_task_path(@task) %> |
    <%= link_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' } %> 
  <% end %>

  <div class="my_subtasks">
	  <% @subtasks.each do |subtask| %>
      <%= render  partial: "subtasks/subtask_show", locals: {subtask: subtask} %>
	  <% end %>
  </div>

  <% if item_owner?(current_user, @task) %>
    <div class="my_subtasks1">
  	 <%= link_to "Create New Subtask", new_subtask_path(task_id: @task.id), remote: true, class: "new_subtask_button" %>
    </div>
  <% end %>